name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # (Change this to 'master' if your default branch is master)

# This is required so the pipeline can push the built web files back to GitHub
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Drift files
        run: dart run build_runner build -d

      - name: Build Web App
        # The base-href MUST match your repo name exactly, surrounded by slashes
        run: flutter build web --release --base-href "/flutter_demo_2026/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web